
# -*- coding: utf-8 -*-
"""CSV analysis with Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxRr7hrWzfoNB7PFaD9be-eh4-SAfbx1
"""

import pandas as pd

data = {
    "Date": pd.date_range(start="2025-06-01", periods=5, freq='D'),
    "Region": ["East", "West", "North", "South", "East"],
    "Salesperson": ["Ravi", "Neha", "Aman", "Priya", "Ravi"],
    "Product": ["Pens", "Notebooks", "Markers", "Staplers", "Pens"],
    "Units Sold": [150, 200, 100, 80, 170],
    "Unit Price": [10, 15, 20, 25, 10]
}

df = pd.DataFrame(data)
df["Total Sales"] = df["Units Sold"] * df["Unit Price"]
print(df)

print("Columns:", df.columns)

print(df.info())

print(df.describe())

sales_by_region = df.groupby("Region")["Total Sales"].sum()
print("Sales by Region")
print(sales_by_region)


