# -*- coding: utf-8 -*-
"""mini_csv_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j2fY1-4HCdSNd2fXVJqCKFf7aI__MLdX
"""

import pandas as pd
df = pd.read_excel('Dataset.xlsx')

df = df.dropna()
df["Total Sales"] = df["Units Sold"] * df["Unit Price"]

print("✅ Total Sales:", df["Total Sales"].sum())
print( )
print("📊 Average Sales by Region:")
print(df.groupby("Region")["Total Sales"].mean())
print( )
print("🏆 Top 2 Salespersons:")
print(df.groupby("Salesperson")["Total Sales"].sum().sort_values(ascending=False).head(2))
print( )
print("🧮 Units Sold Per Product:")
print(df.groupby("Product")["Units Sold"].sum())
print( )
print("🔍 Sales > ₹2000:")
print(df[df["Total Sales"] > 2000])
print( )
print("📈 Sorted by Total Sales:")
print(df.sort_values("Total Sales", ascending=False))