# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5Xj9FaP2umiT6Nxce9HhlA42M736ZDR
"""

num1 = float(input("Enter the first number: "))
operator = input("Enter the operator (+, -, *, /): ")
num2 = float(input("Enter the second number: "))

if operator == '+':
  result = num1 + num2
  print(f"The result is: {result}")
elif operator == '-':
  result = num1 - num2
  print(f"The result is: {result}")
elif operator == '*':
  result = num1 * num2
  print(f"The result is: {result}")
elif operator == '/':
  if num2 == 0:
    print("Error: Division by zero")
  else:
    result = num1 / num2
    print(f"The result is: {result}")
else:
  print("Invalid operator")