# -*- coding: utf-8 -*-
"""Data cleaning code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E16YVEypJ3TJUNy5GsVPqQyHL27KhXw7
"""

import pandas as pd

data = {
    "Name": ["Ravi", "Neha", "Aman", "Ravi", None],
    "Region": ["East", "West", "North", "East", "South"],
    "Sales": [500, 600, None, 500, 300]
}

df = pd.DataFrame(data)

print("Original Data:")
print(df)

df_clean = df.dropna()

print("After removing missing values:")
print(df_clean)

df_no_duplicates = df_clean.drop_duplicates()

print("After removing duplicates:")
print(df_no_duplicates)

east_data = df_no_duplicates[df_no_duplicates["Region"] == "East"]
print("Only East region sales:")
print(east_data)

high_sales = df_no_duplicates[df_no_duplicates["Sales"] > 400]
print("Sales > 400:")
print(high_sales)

sorted_sales = df_no_duplicates.sort_values(by="Sales", ascending=False)
print("Sorted by sales:")
print(sorted_sales)